In [1]:
import numpy as np

img = np.random.randint(0,100,(3,3,2))

初始化img为(3,3,2)大小的三维向量

In [2]:
print(img)

[[[ 4 87]
  [92  5]
  [83 53]]

 [[72 31]
  [72 47]
  [21 84]]

 [[53 27]
  [32 96]
  [39 33]]]


In [4]:
print(img.shape)

(3, 3, 2)


In [5]:
shaped_img = img.reshape(3*3*2,1)

将其转化为列向量

In [6]:
print('after shape: ')
print(shaped_img)

after shape: 
[[ 4]
 [87]
 [92]
 [ 5]
 [83]
 [53]
 [72]
 [31]
 [72]
 [47]
 [21]
 [84]
 [53]
 [27]
 [32]
 [96]
 [39]
 [33]]


In [7]:
print(shaped_img.shape)

(18, 1)


-----
另一种转化为列向量的方式

In [9]:
shaped_img2 = img.reshape(-1,1)

In [10]:
print('second shape:')
print(shaped_img2)
print(shaped_img2.shape)

second shape:
[[ 4]
 [87]
 [92]
 [ 5]
 [83]
 [53]
 [72]
 [31]
 [72]
 [47]
 [21]
 [84]
 [53]
 [27]
 [32]
 [96]
 [39]
 [33]]
(18, 1)
